source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'CocoaBloc', :exclusive => true do
  pod "CocoaBloc", :path => "../"
  pod "CocoaBloc/UIKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod 'LLReactiveMatchers', :git => "https://github.com/lawrencelomax/LLReactiveMatchers.git"
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
