source 'https://github.com/CocoaPods/Specs.git'

target 'CocoaBloc', :exclusive => true do
  pod "CocoaBloc", :path => "../"
  pod "CocoaBloc/UIKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
