language: objective-c
osx_image: xcode7.1
xcode_project: CocoaBloc.xcodeproj

before_install:
    - mkdir tmp
    - git clone https://github.com/Carthage/Carthage.git tmp/Carthage
    - cd ./tmp/Carthage
    - git checkout swift2
    - make package
    - cd ../../
    - sudo installer -pkg ./tmp/Carthage/Carthage.pkg -target /

install:
    - carthage bootstrap --no-use-binaries --use-submodules --platform iOS --verbose
