language: objective-c
osx_image: xcode7.1
xcode_project: CocoaBloc.xcodeproj

before_install:
    - curl -L https://github.com/Carthage/Carthage/releases/download/0.9.4/Carthage.pkg -o Carthage.pkg
    - sudo installer -pkg Carthage.pkg -target /

install:
    - carthage bootstrap --no-use-binaries --use-submodules --no-build
    - carthage build --platform iOS --configuration Debug --no-skip-current
