language: objective-c
osx_image: xcode7.1

before_install:
    - brew update
    - brew install carthage

install:
    - carthage checkout --no-use-binaries --use-submodules

script:
    - carthage build --platform iOS --no-skip-current
