language: objective-c
osx_image: xcode7.1
xcode_project: CocoaBloc.xcodeproj

before_install:
    - brew update
    - brew install carthage

install:
    - carthage bootstrap --no-use-binaries --use-submodules --platform iOS
